// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: types/api/v1beta1/diagnostic.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiagnosticClient is the client API for Diagnostic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagnosticClient interface {
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error)
	GetStacktrace(ctx context.Context, in *GetStacktraceRequest, opts ...grpc.CallOption) (*GetStacktraceResponse, error)
}

type diagnosticClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticClient(cc grpc.ClientConnInterface) DiagnosticClient {
	return &diagnosticClient{cc}
}

func (c *diagnosticClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/tracee.v1beta1.Diagnostic/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticClient) ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error) {
	out := new(ChangeLogLevelResponse)
	err := c.cc.Invoke(ctx, "/tracee.v1beta1.Diagnostic/ChangeLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticClient) GetStacktrace(ctx context.Context, in *GetStacktraceRequest, opts ...grpc.CallOption) (*GetStacktraceResponse, error) {
	out := new(GetStacktraceResponse)
	err := c.cc.Invoke(ctx, "/tracee.v1beta1.Diagnostic/GetStacktrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticServer is the server API for Diagnostic service.
// All implementations must embed UnimplementedDiagnosticServer
// for forward compatibility
type DiagnosticServer interface {
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	ChangeLogLevel(context.Context, *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error)
	GetStacktrace(context.Context, *GetStacktraceRequest) (*GetStacktraceResponse, error)
	mustEmbedUnimplementedDiagnosticServer()
}

// UnimplementedDiagnosticServer must be embedded to have forward compatible implementations.
type UnimplementedDiagnosticServer struct {
}

func (UnimplementedDiagnosticServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedDiagnosticServer) ChangeLogLevel(context.Context, *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeLogLevel not implemented")
}
func (UnimplementedDiagnosticServer) GetStacktrace(context.Context, *GetStacktraceRequest) (*GetStacktraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStacktrace not implemented")
}
func (UnimplementedDiagnosticServer) mustEmbedUnimplementedDiagnosticServer() {}

// UnsafeDiagnosticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticServer will
// result in compilation errors.
type UnsafeDiagnosticServer interface {
	mustEmbedUnimplementedDiagnosticServer()
}

func RegisterDiagnosticServer(s grpc.ServiceRegistrar, srv DiagnosticServer) {
	s.RegisterService(&Diagnostic_ServiceDesc, srv)
}

func _Diagnostic_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracee.v1beta1.Diagnostic/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnostic_ChangeLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).ChangeLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracee.v1beta1.Diagnostic/ChangeLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).ChangeLogLevel(ctx, req.(*ChangeLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnostic_GetStacktrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStacktraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).GetStacktrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracee.v1beta1.Diagnostic/GetStacktrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).GetStacktrace(ctx, req.(*GetStacktraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Diagnostic_ServiceDesc is the grpc.ServiceDesc for Diagnostic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Diagnostic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracee.v1beta1.Diagnostic",
	HandlerType: (*DiagnosticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _Diagnostic_GetMetrics_Handler,
		},
		{
			MethodName: "ChangeLogLevel",
			Handler:    _Diagnostic_ChangeLogLevel_Handler,
		},
		{
			MethodName: "GetStacktrace",
			Handler:    _Diagnostic_GetStacktrace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/api/v1beta1/diagnostic.proto",
}
